# Exclude file types that can't be open in vim (FZF_DEFAULT_IGNORE is used for fzf.vim)
export IGNORE_FILE_EXT=""
IGNORE_FILE_EXT+="gz\|tar\|rar\|zip\|7z"
IGNORE_FILE_EXT+="\|min.js\|min.map"
IGNORE_FILE_EXT+="\|pdf\|doc\|docx"
IGNORE_FILE_EXT+="\|ppt\|pptx"
IGNORE_FILE_EXT+="\|gif\|jpeg\|jpg\|png\|svg"
IGNORE_FILE_EXT+="\|psd\|xcf"
IGNORE_FILE_EXT+="\|ai\|epub\|kpf\|mobi"
IGNORE_FILE_EXT+="\|snap"
IGNORE_FILE_EXT+="\|TTF\|ttf\|otf\|eot\|woff\|woff2"
IGNORE_FILE_EXT+="\|wma\|mp3\|m4a\|ape\|ogg\|opus\|flac"
IGNORE_FILE_EXT+="\|mp4\|wmv\|avi\|mkv\|webm\|m4b"
IGNORE_FILE_EXT+="\|musicdb\|itdb\|itl\|itc"
IGNORE_FILE_EXT+="\|o\|so\|dll"
IGNORE_FILE_EXT+="\|cbor\|msgpack"
IGNORE_FILE_EXT+="\|wpj"
IGNORE_FILE_EXT+="\|pyc"
IGNORE_FILE_EXT+="\|js.map"

export IGNORE_FILE_WILD=""
IGNORE_FILE_WILD+="^snap\/"
IGNORE_FILE_WILD+="\|^cache\|^_cache"
IGNORE_FILE_WILD+="\|Library\|^Cache"  # mac
IGNORE_FILE_WILD+="\|AppData"  # Windows
IGNORE_FILE_WILD+="\|Android"
IGNORE_FILE_WILD+="\|site-packages\|egg-info\|dist-info"
IGNORE_FILE_WILD+="\|node-gyp\|node_modules\|bower_components"
IGNORE_FILE_WILD+="\|^build\|webpack_bundles"
IGNORE_FILE_WILD+="\|json\/test\/data"  # sdl2-playproject
IGNORE_FILE_WILD+="\|drive_[a-z]\/"  # WINE (esp if created in lutris)
IGNORE_FILE_WILD+="\|\^\?\(\.\/\)snap\/"  # $HOME/snap/ (when FZF invoked via home directory)
IGNORE_FILE_WILD+="\|^snap\/"  # $HOME/snap/ (when FZF invoked via home directory)
IGNORE_FILE_WILD+="\|\/gems\/"  # canvas-lms
IGNORE_FILE_WILD+="\|^work\/\|^study\/"  # canvas-lms
IGNORE_FILE_WILD+="\|__pycache__\/"  # python
IGNORE_FILE_WILD+="\|^\.cache\/"  # webpack, so on
IGNORE_FILE_WILD+="\|\(_\)\?build\/"  # output directories for static files
IGNORE_FILE_WILD+="\|__generated__\/"  # relay
