~/work/peergrade/:
  curlify:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/curlify.git
      tony: git+ssh://git@github.com/tony/curlify.git
    repo: git+https://github.com/ofw/curlify.git
  django-assets:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/django-assets.git
      tony: git+ssh://git@github.com/tony/django-assets.git
    repo: git+https://github.com/miracle2k/django-assets.git
  django-celery-monitor:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/django-celery-monitor.git
      tony: git+ssh://git@github.com/tony/django-celery-monitor.git
    repo: git+https://github.com/jezdez/django-celery-monitor.git
  django-mongoengine:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/django-mongoengine.git
    repo: git+https://github.com/MongoEngine/django-mongoengine.git
  django-rq-dashboard:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/django-rq-dashboard.git
      morlandi: git+ssh://git@github.com/morlandi/django-rq-dashboard.git
      sbussetti: git+ssh://git@github.com/sbussetti/django-rq-dashboard.git
    repo: git+https://github.com/brutasse/django-rq-dashboard.git
  django-webpack-loader:
    remotes:
      alihazemfarouk: git+ssh://git@github.com/alihazemfarouk/django-webpack-loader.git
      develtech: git+ssh://git@github.com/develtech/django-webpack-loader.git
      eduflow: git+ssh://git@github.com/eduflow/django-webpack-loader.git
      naivefeeling-flask-webpack-loader: git+ssh://git@github.com/naivefeeling/flask-webpack-loader.git
      tony: git+ssh://git@github.com/tony/django-webpack-loader.git
    repo: git+https://github.com/owais/django-webpack-loader.git
  eduflow-api-examples:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/api-examples.git
      tony: git+ssh://git@github.com/tony/api-examples.git
    repo: git+ssh://git@github.com/eduflow/api-examples.git
  extras-mongoengine:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/extras-mongoengine.git
    repo: git+https://github.com/MongoEngine/extras-mongoengine.git
  fakeredis:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/fakeredis.git
      tony: git+ssh://git@github.com/tony/fakeredis.git
    repo: git+https://github.com/jamesls/fakeredis.git
  flask:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/flask.git
      tony: git+ssh://git@github.com/tony/flask.git
    repo: git+https://github.com/mitsuhiko/flask.git
  flask-admin:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/flask-admin.git
    repo: git+https://github.com/flask-admin/flask-admin.git
  flask-mongoengine:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/flask-mongoengine.git
    repo: git+https://github.com/MongoEngine/flask-mongoengine.git
  mmh3:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/mmh3.git
      honnibal: git+ssh://git@github.com/honnibal/mmh3.git
      tony: git+ssh://git@github.com/tony/mmh3.git
    repo: git+https://github.com/hajimes/mmh3.git
  mongoengine-objectidmapfield:
    repo: git+https://github.com/eduflow/mongoengine-objectidmapfield.git
  mongoengine-slugfield:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/mongoengine-slugfield.git
    repo: git+https://github.com/bennylope/mongoengine-extras.git
  pymongo-basic-profiler:
    repo: git+ssh://git@github.com/eduflow/pymongo-basic-profiler.git
  python-saml:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/python-saml.git
    repo: git+https://github.com/onelogin/python-saml.git
  python-socketio:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/python-socketio.git
    repo: git+https://github.com/miguelgrinberg/python-socketio.git
  python3-saml:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/python3-saml.git
    repo: git+https://github.com/onelogin/python3-saml.git
  quill:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/quill.git
      tony: git+ssh://git@github.com/tony/quill.git
    repo: git+https://github.com/quilljs/quill.git
  react-google-picker:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/react-google-picker.git
      tony: git+ssh://git@github.com/tony/react-google-picker.git
    repo: git+https://github.com/sdoomz/react-google-picker.git
  react-plyr:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/react-plyr.git
      tony: git+ssh://git@github.com/tony/react-plyr.git
    repo: git+https://github.com/xDae/react-plyr.git
  react-quill:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/react-quill.git
      tony: git+ssh://git@github.com/tony/react-quill.git
    repo: git+https://github.com/zenoamaro/react-quill.git
  sphinx-graphiql:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/sphinx-graphiql.git
    repo: git+https://github.com/hasura/sphinx-graphiql.git
  videojs-record:
    remotes:
      eduflow: git+ssh://git@github.com/eduflow/videojs-record.git
      tony: git+ssh://git@github.com/tony/videojs-record.git
    repo: git+https://github.com/collab-project/videojs-record.git
  webpack-bundle-tracker:
    remotes:
      alihazemfarouk: git+ssh://git@github.com/alihazemfarouk/webpack-bundle-tracker.git
      develtech: git+ssh://git@github.com/develtech/webpack-bundle-tracker.git
      eduflow: git+ssh://git@github.com/eduflow/webpack-bundle-tracker.git
      tony: git+ssh://git@github.com/tony/webpack-bundle-tracker.git
    repo: git+https://github.com/owais/webpack-bundle-tracker.git
